handle promise rejections as well
grainrigi/async-singleton pull request #1
Opened 2020-10-26 15:56 UTC by Alahel

* handle promises rejections in the chain

2020-10-30 08:32 UTC, grainrigi requested changes
Thank you for your contribution.
Please check the reviewes before I can merge your request.

2020-10-30 08:32 UTC, grainrigi commented on src/index.ts
> +type QueueItem = { resolve: (val: any) => any, reject: (val: any) => any, args: any[] }
Do not omit semicolon

2020-10-30 08:32 UTC, grainrigi commented on src/index.ts
> +      let context = find(contexts, (v: any) => isEqual(slicer(args), slicer(v.args)));
Unnecessarry type annotation since element type can be inferred

2020-10-30 08:32 UTC, grainrigi commented on src/index.ts
> +      let errorResult: any
Do not omit semicolon

2020-10-30 08:32 UTC, grainrigi commented on src/index.ts
> +        reject(errorResult)
Do not omit semicolon

2020-10-30 08:32 UTC, grainrigi commented on src/index.ts
> +            errorResult = e
Do not omit semicolon

2020-10-30 08:32 UTC, grainrigi commented on src/index.ts
> +          return resolve(result)
Do not omit semicolon

2020-10-30 08:32 UTC, grainrigi commented on src/index.ts
> +      remove(contexts, (v: any) => isEqual(slicer(args), slicer(v.args)));
Unnecessarry type annotation

2020-11-05 15:28 UTC, Alahel commented
> Thank you for your contribution.
> Please check the reviewes before I can merge your request.

Thanks for the review :+1:

2020-11-06 23:46 UTC, grainrigi commented
Everything looks good to me.
Thanks!

2020-11-06 23:46 UTC, merged